# Generated by Django 6.0.4 on 2026-05-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main", "0002_galleryimage_material_uploaded_by_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GalleryImage",
        ),
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["name"],
                "verbose_name": "Роль",
                "verbose_name_plural": "Роли",
            },
        ),
        migrations.RemoveField(
            model_name="material",
            name="uploaded_by",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="customuser_set", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="customuser_set", to="auth.permission"
            ),
        ),
    ]
